# Generated by Django 2.2.7 on 2019-11-27 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likeStars',
        ),
        migrations.AddField(
            model_name='user',
            name='likestars',
            field=models.ManyToManyField(blank=True, to='stars.Star'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likestalkers',
            field=models.ManyToManyField(blank=True, related_name='likecomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='likemovies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
