# Generated by Django 2.2.4 on 2019-12-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('deathday', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('homepage', models.TextField()),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TagedImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrops', models.TextField()),
                ('posters', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_from', to='stars.Star')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('to_star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_to', to='stars.Star')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star')),
            ],
            options={
                'order_with_respect_to': 'movie',
            },
        ),
    ]
